prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/petty_cash_quick_access.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/navigation/lists/petty_cash_admin_quick_list.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/data_load_wizard_progress_reminder_data.sql
@@application/shared_components/navigation/lists/data_load_wizard_progress_reminder_data_002.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/app_54293_logo_1_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/ap_accountants.sql
@@application/shared_components/security/authorizations/hrss_approvers.sql
@@application/shared_components/security/authorizations/treasury.sql
@@application/shared_components/security/app_access_control/employee.sql
@@application/shared_components/security/app_access_control/hrss_approver.sql
@@application/shared_components/security/app_access_control/ap_accountant.sql
@@application/shared_components/security/app_access_control/treasury.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/dct_imprest_count.sql
@@application/shared_components/logic/application_items/emp_name.sql
@@application/shared_components/logic/application_items/emp_num.sql
@@application/shared_components/logic/application_items/emp_org_id.sql
@@application/shared_components/logic/application_items/fab_debit_card_count.sql
@@application/shared_components/logic/application_items/get_id.sql
@@application/shared_components/logic/application_items/is_fbp_emp.sql
@@application/shared_components/logic/application_items/is_petty_cash_admin.sql
@@application/shared_components/logic/application_items/p16_er_count.sql
@@application/shared_components/logic/application_items/p2_petty_cash_count.sql
@@application/shared_components/logic/application_items/person_id.sql
@@application/shared_components/logic/application_items/user_cost_center.sql
@@application/shared_components/logic/application_computations/person_id.sql
@@application/shared_components/logic/application_computations/fab_debit_card_count.sql
@@application/shared_components/logic/application_computations/dct_imprest_count.sql
@@application/shared_components/logic/application_computations/emp_org_id.sql
@@application/shared_components/logic/application_computations/emp_name.sql
@@application/shared_components/logic/application_computations/emp_num.sql
@@application/shared_components/logic/application_computations/is_petty_cash_admin.sql
@@application/shared_components/logic/application_computations/p2_petty_cash_count.sql
@@application/shared_components/logic/application_computations/user_cost_center.sql
@@application/shared_components/logic/application_computations/is_fbp_emp.sql
@@application/shared_components/logic/application_computations/p16_er_count.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/all_organizations_with_details_lov.sql
@@application/shared_components/user_interface/lovs/copy_of_departments_system_lov.sql
@@application/shared_components/user_interface/lovs/copy_of_organizations_all_lov.sql
@@application/shared_components/user_interface/lovs/cost_centers_with_names_lov.sql
@@application/shared_components/user_interface/lovs/copy_of_status_lov.sql
@@application/shared_components/user_interface/lovs/data_load_charset.sql
@@application/shared_components/user_interface/lovs/data_load_option.sql
@@application/shared_components/user_interface/lovs/date_format_opt.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/employee_name_and_number_return_emp_num.sql
@@application/shared_components/user_interface/lovs/employee_name_by_personid_lov.sql
@@application/shared_components/user_interface/lovs/employees_all_lov.sql
@@application/shared_components/user_interface/lovs/employees_by_username.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/manual_employee_num_lov.sql
@@application/shared_components/user_interface/lovs/petty_cash_open_for_clearing.sql
@@application/shared_components/user_interface/lovs/petty_cash_numbers.sql
@@application/shared_components/user_interface/lovs/petty_cash_purpose_existing.sql
@@application/shared_components/user_interface/lovs/petty_cash_purpose_new.sql
@@application/shared_components/user_interface/lovs/petty_cash_types.sql
@@application/shared_components/user_interface/lovs/priority.sql
@@application/shared_components/user_interface/lovs/projects_by_departments.sql
@@application/shared_components/user_interface/lovs/task_by_projects_page90.sql
@@application/shared_components/user_interface/lovs/tasks_by_project.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/yes_lov.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/reports/report_queries/expensereportdetails.sql
@@application/shared_components/reports/report_queries/expensereportdetails3.sql
@@application/shared_components/reports/report_queries/expensereportdetails4.sql
@@application/shared_components/reports/report_queries/petty_cash_details.sql
@@application/shared_components/reports/report_layouts/expensereportdetails.sql
@@application/shared_components/reports/report_layouts/expense_report_details.sql
@@application/shared_components/reports/report_layouts/expensereportdetails4.sql
@@application/shared_components/reports/report_layouts/petty_cash_details.sql
@@application/shared_components/email/templates/delegate_petty_cash.sql
@@application/shared_components/email/templates/petty_cash_invitation.sql
@@application/shared_components/email/templates/petty_cash_fbp_email.sql
@@application/shared_components/email/templates/approve_reject_petty_cash.sql
@@application/shared_components/email/templates/final_approve_petty_cash.sql
@@application/shared_components/email/templates/final_reject_petty_cash.sql
@@application/shared_components/email/templates/fyi_approve_petty_cash.sql
@@application/shared_components/email/templates/approve_reject_expense_report.sql
@@application/shared_components/email/templates/final_approve_expense_report.sql
@@application/shared_components/email/templates/final_reject_expense_report.sql
@@application/shared_components/email/templates/remindar_approve_reject_petty_cash.sql
@@application/shared_components/email/templates/reminder_approve_reject_expense_report.sql
@@application/shared_components/email/templates/collaborate_petty_cash.sql
@@application/shared_components/email/templates/temp_closeing_reminder.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/shared_components/security/authentications/dct.sql
@@application/shared_components/plugins/dynamic_action/apex_profile_menu.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_badge_list.sql
@@application/shared_components/plugins/dynamic_action/apex_notification.sql
@@application/shared_components/data_loading/tables/hrss_petty_cash_reminders.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00090.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10011.sql
@@application/pages/page_10013.sql
@@application/pages/page_10014.sql
@@application/pages/page_10020.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
