-- ===========================================================================
-- General Ledger (App 210) - Layer 6 - seed (GENERATED by gen_seed.py)
-- Sectors + cost-center mappings, Chapters + appropriation mappings,
-- PBB DCT-Program hierarchy + description-matched program mappings.
-- Re-runnable: seed mappings tagged created_by='SEED' and cleared first.
-- ===========================================================================
SET DEFINE OFF
SET SQLBLANKLINES ON
ALTER SESSION DISABLE PARALLEL DML;

-- ---- dimension catalog ----
MERGE INTO prod.dct_gl_class_type t USING (SELECT 'SECTOR' code FROM dual) s
  ON (t.class_type_code = s.code)
WHEN NOT MATCHED THEN INSERT (class_type_code,name_en,name_ar,segment_key,seg_pad_width,seg_prefix,is_hierarchical,display_order,is_active,created_by)
  VALUES ('SECTOR','Sector','القطاع','COST_CENTER',7,NULL,'N',10,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Sector',t.name_ar='القطاع',t.segment_key='COST_CENTER',t.seg_pad_width=7,t.is_hierarchical='N',t.display_order=10;

MERGE INTO prod.dct_gl_class_type t USING (SELECT 'CHAPTER' code FROM dual) s
  ON (t.class_type_code = s.code)
WHEN NOT MATCHED THEN INSERT (class_type_code,name_en,name_ar,segment_key,seg_pad_width,seg_prefix,is_hierarchical,display_order,is_active,created_by)
  VALUES ('CHAPTER','Chapter','الباب','APPROPRIATION',6,NULL,'N',20,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Chapter',t.name_ar='الباب',t.segment_key='APPROPRIATION',t.seg_pad_width=6,t.is_hierarchical='N',t.display_order=20;

MERGE INTO prod.dct_gl_class_type t USING (SELECT 'DCT_PROGRAM' code FROM dual) s
  ON (t.class_type_code = s.code)
WHEN NOT MATCHED THEN INSERT (class_type_code,name_en,name_ar,segment_key,seg_pad_width,seg_prefix,is_hierarchical,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','DCT Program','البرنامج','PROGRAM_CODE',6,NULL,'Y',30,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='DCT Program',t.name_ar='البرنامج',t.segment_key='PROGRAM_CODE',t.seg_pad_width=6,t.is_hierarchical='Y',t.display_order=30;

-- ---- Sector values ----
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'AD_GUGGENHEIM_MUSEUM' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','AD_GUGGENHEIM_MUSEUM','AD-Guggenheim Museum',NULL,NULL,10,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='AD-Guggenheim Museum',t.parent_value_id=NULL,t.tag=NULL,t.display_order=10;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'ALC' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','ALC','ALC',NULL,NULL,20,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='ALC',t.parent_value_id=NULL,t.tag=NULL,t.display_order=20;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'CULTURE' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','CULTURE','Culture',NULL,NULL,30,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Culture',t.parent_value_id=NULL,t.tag=NULL,t.display_order=30;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'CWIP' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','CWIP','CWIP',NULL,NULL,40,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='CWIP',t.parent_value_id=NULL,t.tag=NULL,t.display_order=40;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'EXECUTIVE_OFFICE' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','EXECUTIVE_OFFICE','Executive Office',NULL,NULL,50,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Executive Office',t.parent_value_id=NULL,t.tag=NULL,t.display_order=50;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'HERITAGE_CULTURE_COMMITTEE' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','HERITAGE_CULTURE_COMMITTEE','Heritage & Culture Committee',NULL,NULL,60,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Heritage & Culture Committee',t.parent_value_id=NULL,t.tag=NULL,t.display_order=60;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'INTERNAL_AUDIT' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','INTERNAL_AUDIT','Internal Audit',NULL,NULL,70,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Internal Audit',t.parent_value_id=NULL,t.tag=NULL,t.display_order=70;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'LEGAL_GOVERNMENT_AFFAIRS' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','LEGAL_GOVERNMENT_AFFAIRS','Legal & Government Affairs',NULL,NULL,80,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Legal & Government Affairs',t.parent_value_id=NULL,t.tag=NULL,t.display_order=80;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'LOUVRE_ABU_DHABI' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','LOUVRE_ABU_DHABI','Louvre Abu Dhabi',NULL,NULL,90,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Louvre Abu Dhabi',t.parent_value_id=NULL,t.tag=NULL,t.display_order=90;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'MUSEUMS' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','MUSEUMS','Museums',NULL,NULL,100,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Museums',t.parent_value_id=NULL,t.tag=NULL,t.display_order=100;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'MUSEUM_SHARED_SERVICES' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','MUSEUM_SHARED_SERVICES','Museum Shared Services',NULL,NULL,110,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Museum Shared Services',t.parent_value_id=NULL,t.tag=NULL,t.display_order=110;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'NATURAL_HISTORY_MUSEUM' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','NATURAL_HISTORY_MUSEUM','Natural History Museum',NULL,NULL,120,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Natural History Museum',t.parent_value_id=NULL,t.tag=NULL,t.display_order=120;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'PROJECTS_MANAGEMENT_ENGINEERING' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','PROJECTS_MANAGEMENT_ENGINEERING','Projects Management & Engineering',NULL,NULL,130,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Projects Management & Engineering',t.parent_value_id=NULL,t.tag=NULL,t.display_order=130;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'STRATEGIC_AFFAIRS' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','STRATEGIC_AFFAIRS','Strategic Affairs',NULL,NULL,140,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Strategic Affairs',t.parent_value_id=NULL,t.tag=NULL,t.display_order=140;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'STRATEGIC_MARKETING_COMMUNICATION' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','STRATEGIC_MARKETING_COMMUNICATION','Strategic Marketing & Communication',NULL,NULL,150,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Strategic Marketing & Communication',t.parent_value_id=NULL,t.tag=NULL,t.display_order=150;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'STRATEGY_POLICY' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','STRATEGY_POLICY','Strategy & Policy',NULL,NULL,160,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Strategy & Policy',t.parent_value_id=NULL,t.tag=NULL,t.display_order=160;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'SUPPORT_SERVICE' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','SUPPORT_SERVICE','Support Service',NULL,NULL,170,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Support Service',t.parent_value_id=NULL,t.tag=NULL,t.display_order=170;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'TEAMLAB' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','TEAMLAB','TeamLab',NULL,NULL,180,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='TeamLab',t.parent_value_id=NULL,t.tag=NULL,t.display_order=180;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'TENDERING_AND_PROJECTS_CONTROL' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','TENDERING_AND_PROJECTS_CONTROL','Tendering and Projects Control',NULL,NULL,190,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Tendering and Projects Control',t.parent_value_id=NULL,t.tag=NULL,t.display_order=190;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'TOURISM' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','TOURISM','Tourism',NULL,NULL,200,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Tourism',t.parent_value_id=NULL,t.tag=NULL,t.display_order=200;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'SECTOR' ct,'ZAYED_NATIONAL_MUSEUM' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('SECTOR','ZAYED_NATIONAL_MUSEUM','Zayed National Museum',NULL,NULL,210,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Zayed National Museum',t.parent_value_id=NULL,t.tag=NULL,t.display_order=210;

-- ---- Chapter values ----
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'CHAPTER' ct,'CH1' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('CHAPTER','CH1','Chapter 1',NULL,'Payroll',10,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Chapter 1',t.parent_value_id=NULL,t.tag='Payroll',t.display_order=10;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'CHAPTER' ct,'CH2' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('CHAPTER','CH2','Chapter 2',NULL,'Opex',20,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Chapter 2',t.parent_value_id=NULL,t.tag='Opex',t.display_order=20;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'CHAPTER' ct,'CH3' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('CHAPTER','CH3','Chapter 3',NULL,'Capex',30,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Chapter 3',t.parent_value_id=NULL,t.tag='Capex',t.display_order=30;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'CHAPTER' ct,'CH4' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('CHAPTER','CH4','Chapter 4',NULL,'Subsidy',40,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Chapter 4',t.parent_value_id=NULL,t.tag='Subsidy',t.display_order=40;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'CHAPTER' ct,'CH5' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('CHAPTER','CH5','Chapter 5',NULL,'Aids & Grants',50,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Chapter 5',t.parent_value_id=NULL,t.tag='Aids & Grants',t.display_order=50;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'CHAPTER' ct,'CH6' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('CHAPTER','CH6','Chapter 6',NULL,'CWIP',60,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Chapter 6',t.parent_value_id=NULL,t.tag='CWIP',t.display_order=60;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'CHAPTER' ct,'STIMULUS' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('CHAPTER','STIMULUS','Stimulus',NULL,'Stimulus',70,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Stimulus',t.parent_value_id=NULL,t.tag='Stimulus',t.display_order=70;

-- ---- DCT Program values (parents first, then children) ----
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070100' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070100','Support Services',NULL,NULL,10,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Support Services',t.parent_value_id=NULL,t.tag=NULL,t.display_order=10;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070200' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070200','Culture Management, and Preservation',NULL,NULL,20,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Culture Management, and Preservation',t.parent_value_id=NULL,t.tag=NULL,t.display_order=20;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070300' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070300','Culture and Creative Industry development',NULL,NULL,30,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Culture and Creative Industry development',t.parent_value_id=NULL,t.tag=NULL,t.display_order=30;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070400' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070400','Museums Operations and Development',NULL,NULL,40,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Museums Operations and Development',t.parent_value_id=NULL,t.tag=NULL,t.display_order=40;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070500' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070500','Tourism Development Program',NULL,NULL,50,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Tourism Development Program',t.parent_value_id=NULL,t.tag=NULL,t.display_order=50;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070600' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070600','Marketing and Promotion',NULL,NULL,60,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Marketing and Promotion',t.parent_value_id=NULL,t.tag=NULL,t.display_order=60;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070700' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070700','ALC',NULL,NULL,70,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='ALC',t.parent_value_id=NULL,t.tag=NULL,t.display_order=70;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070101' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070101','Corporate Office',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,80,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Corporate Office',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=80;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070102' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070102','Finance',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,90,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Finance',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=90;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070103' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070103','Human Resource (HR)',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,100,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Human Resource (HR)',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=100;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070104' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070104','Communication & Public Relations (PR)',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,110,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Communication & Public Relations (PR)',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=110;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070105' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070105','Procurement',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,120,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Procurement',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=120;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070106' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070106','Information and Communication Technology (ICT)',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,130,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Information and Communication Technology (ICT)',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=130;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070107' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070107','General services',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,140,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='General services',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=140;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070108' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070108','Legal Affairs',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,150,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Legal Affairs',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=150;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070109' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070109','Internal Audit and Risk Management',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,160,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Internal Audit and Risk Management',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=160;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070110' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070110','Strategic Planning',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,170,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Strategic Planning',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=170;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070111' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070111','Digital Transformation, Data Management & AI',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),NULL,180,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Digital Transformation, Data Management & AI',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070100'),t.tag=NULL,t.display_order=180;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070201' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070201','Heritage Site Management',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),NULL,190,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Heritage Site Management',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),t.tag=NULL,t.display_order=190;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070202' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070202','Cultural Education',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),NULL,200,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Cultural Education',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),t.tag=NULL,t.display_order=200;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070203' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070203','Collection management',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),NULL,210,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Collection management',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),t.tag=NULL,t.display_order=210;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070204' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070204','Cultural Preservation',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),NULL,220,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Cultural Preservation',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),t.tag=NULL,t.display_order=220;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070205' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070205','Cultural site management',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),NULL,230,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Cultural site management',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),t.tag=NULL,t.display_order=230;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070206' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070206','Cultural Events',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),NULL,240,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Cultural Events',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070200'),t.tag=NULL,t.display_order=240;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070301' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070301','Creative Industry development',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070300'),NULL,250,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Creative Industry development',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070300'),t.tag=NULL,t.display_order=250;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070302' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070302','Regulatory and Capacity Building (Culture)',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070300'),NULL,260,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Regulatory and Capacity Building (Culture)',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070300'),t.tag=NULL,t.display_order=260;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070303' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070303','Cultural Industries Development',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070300'),NULL,270,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Cultural Industries Development',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070300'),t.tag=NULL,t.display_order=270;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070401' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070401','Museums Operations',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070400'),NULL,280,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Museums Operations',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070400'),t.tag=NULL,t.display_order=280;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070402' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070402','Museums development',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070400'),NULL,290,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Museums development',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070400'),t.tag=NULL,t.display_order=290;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070403' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070403','Museum Obligation',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070400'),NULL,300,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Museum Obligation',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070400'),t.tag=NULL,t.display_order=300;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070501' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070501','Tourism attraction and activities',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070500'),NULL,310,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Tourism attraction and activities',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070500'),t.tag=NULL,t.display_order=310;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070502' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070502','Regulatory and Capacity Building (Tourism)',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070500'),NULL,320,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Regulatory and Capacity Building (Tourism)',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070500'),t.tag=NULL,t.display_order=320;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070503' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070503','Enhance Visitor Experience',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070500'),NULL,330,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Enhance Visitor Experience',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070500'),t.tag=NULL,t.display_order=330;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070601' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070601','Destination Marketing',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070600'),NULL,340,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Destination Marketing',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070600'),t.tag=NULL,t.display_order=340;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070602' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070602','Global Awareness and Outreach',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070600'),NULL,350,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Global Awareness and Outreach',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070600'),t.tag=NULL,t.display_order=350;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070603' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070603','Culture awareness and outreach',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070600'),NULL,360,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='Culture awareness and outreach',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070600'),t.tag=NULL,t.display_order=360;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070701' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070701','ALC Development & Research',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),NULL,370,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='ALC Development & Research',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),t.tag=NULL,t.display_order=370;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070702' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070702','ALC Awards and grants',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),NULL,380,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='ALC Awards and grants',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),t.tag=NULL,t.display_order=380;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070703' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070703','ALC Events',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),NULL,390,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='ALC Events',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),t.tag=NULL,t.display_order=390;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070704' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070704','ALC Advancing readership',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),NULL,400,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='ALC Advancing readership',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),t.tag=NULL,t.display_order=400;
MERGE INTO prod.dct_gl_class_value t USING (SELECT 'DCT_PROGRAM' ct,'P070705' vc FROM dual) s
  ON (t.class_type_code = s.ct AND t.value_code = s.vc)
WHEN NOT MATCHED THEN INSERT (class_type_code,value_code,name_en,parent_value_id,tag,display_order,is_active,created_by)
  VALUES ('DCT_PROGRAM','P070705','ALC Promotion',(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),NULL,410,'Y','SEED')
WHEN MATCHED THEN UPDATE SET t.name_en='ALC Promotion',t.parent_value_id=(SELECT class_value_id FROM prod.dct_gl_class_value WHERE class_type_code='DCT_PROGRAM' AND value_code='P070700'),t.tag=NULL,t.display_order=410;

-- ---- clear prior seed mappings (re-runnable) ----
DELETE FROM prod.dct_gl_seg_class_map WHERE created_by='SEED';

-- ---- Sector mappings (cost_center -> sector) ----
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510011',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='EXECUTIVE_OFFICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510100',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='EXECUTIVE_OFFICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510110',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='EXECUTIVE_OFFICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510120',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='LOUVRE_ABU_DHABI';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510121',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='LOUVRE_ABU_DHABI';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510122',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='LOUVRE_ABU_DHABI';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510123',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='LOUVRE_ABU_DHABI';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510124',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='LOUVRE_ABU_DHABI';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510125',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='LOUVRE_ABU_DHABI';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510126',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='LOUVRE_ABU_DHABI';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510127',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='LOUVRE_ABU_DHABI';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510130',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGY_POLICY';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510140',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='INTERNAL_AUDIT';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510142',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TEAMLAB';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510150',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CWIP';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510155',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TENDERING_AND_PROJECTS_CONTROL';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510160',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='LEGAL_GOVERNMENT_AFFAIRS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510170',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='SUPPORT_SERVICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510175',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_MARKETING_COMMUNICATION';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510180',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ZAYED_NATIONAL_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510181',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ZAYED_NATIONAL_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510182',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ZAYED_NATIONAL_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510183',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ZAYED_NATIONAL_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510184',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ZAYED_NATIONAL_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510185',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ZAYED_NATIONAL_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510195',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510200',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='SUPPORT_SERVICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510201',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='SUPPORT_SERVICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510202',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='MUSEUMS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510210',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='SUPPORT_SERVICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510220',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='SUPPORT_SERVICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510230',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='SUPPORT_SERVICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510240',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='SUPPORT_SERVICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510250',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='SUPPORT_SERVICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510310',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510311',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510320',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510321',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510322',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510330',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510331',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510332',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510340',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510341',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510342',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='NATURAL_HISTORY_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4510410',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='AD_GUGGENHEIM_MUSEUM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511000',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511010',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511011',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511020',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511150',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511250',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511300',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511550',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511600',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511700',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511750',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4511800',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4512000',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_AFFAIRS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4512010',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_AFFAIRS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4512100',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_AFFAIRS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4512200',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_AFFAIRS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4512300',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_AFFAIRS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4512500',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_AFFAIRS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4512600',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='EXECUTIVE_OFFICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4513000',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_MARKETING_COMMUNICATION';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4513110',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_MARKETING_COMMUNICATION';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4513111',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_MARKETING_COMMUNICATION';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4513120',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_MARKETING_COMMUNICATION';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4513130',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_MARKETING_COMMUNICATION';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4513140',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_MARKETING_COMMUNICATION';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4514000',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='MUSEUM_SHARED_SERVICES';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4514120',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='MUSEUM_SHARED_SERVICES';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4514121',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='MUSEUM_SHARED_SERVICES';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4514130',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='MUSEUM_SHARED_SERVICES';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4514140',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='MUSEUM_SHARED_SERVICES';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4514150',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='MUSEUM_SHARED_SERVICES';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4514160',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='MUSEUM_SHARED_SERVICES';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4514180',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='MUSEUM_SHARED_SERVICES';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515000',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515001',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515010',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515020',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515030',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515040',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515100',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515300',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515400',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515500',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515600',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='STRATEGIC_MARKETING_COMMUNICATION';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515700',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4515900',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='TOURISM';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4516100',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='CULTURE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4517000',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='HERITAGE_CULTURE_COMMITTEE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4517010',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='HERITAGE_CULTURE_COMMITTEE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4517100',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='HERITAGE_CULTURE_COMMITTEE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4517150',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='HERITAGE_CULTURE_COMMITTEE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4517200',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='HERITAGE_CULTURE_COMMITTEE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4517250',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='HERITAGE_CULTURE_COMMITTEE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4518113',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='EXECUTIVE_OFFICE';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4519196',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4519197',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4519198',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4519199',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4519200',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4519201',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4519202',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4519203',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'SECTOR','4519204',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='SECTOR' AND value_code='ALC';

-- ---- Chapter mappings (appropriation -> chapter) ----
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','000438',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='STIMULUS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','000440',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='STIMULUS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','000442',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='STIMULUS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','000879',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='STIMULUS';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','050397',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','050723',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','050727',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','050728',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','050729',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','050730',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','050731',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','100103',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH1';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','100905',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH1';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','101553',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH1';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','101832',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH1';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','200104',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','200657',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','200776',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','200906',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','200989',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','200990',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201004',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201080',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201096',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201098',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201128',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201182',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201257',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201350',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201450',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201458',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201502',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201554',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201632',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201644',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201678',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201736',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201746',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201760',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201761',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201763',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201776',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201833',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201868',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201906',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201919',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201931',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','201932',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','202061',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','202067',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','250042',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','250043',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','250044',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH2';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','300105',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','300658',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','300907',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','301005',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','301099',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','301439',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','301451',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','301555',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','301737',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','301762',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','301834',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','301907',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','350045',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','350046',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH3';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','402025',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH4';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','402066',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH4';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','500748',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH5';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','502012',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH5';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','502026',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH5';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','502175',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH5';
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by) SELECT 'CHAPTER','600232',class_value_id,DATE '2024-01-01',NULL,'SEED' FROM prod.dct_gl_class_value WHERE class_type_code='CHAPTER' AND value_code='CH6';

-- ---- DCT Program mappings (program_code used in combinations, matched to PBB by description) ----
INSERT INTO prod.dct_gl_seg_class_map (class_type_code,segment_value,class_value_id,start_date,end_date,created_by)
SELECT 'DCT_PROGRAM', prod.dct_gl_class_pkg.norm(p.program_code,6), cv.class_value_id, DATE '2024-01-01', NULL, 'SEED'
FROM (SELECT DISTINCT program_code FROM prod.gl_src_combinations WHERE program_code IS NOT NULL) p
JOIN prod.gl_src_program gp ON gp.program_code = p.program_code
JOIN prod.dct_gl_class_value cv ON cv.class_type_code='DCT_PROGRAM'
  AND UPPER(TRIM(cv.name_en)) = UPPER(TRIM(gp.program_description))
WHERE NOT EXISTS (SELECT 1 FROM prod.dct_gl_seg_class_map m
  WHERE m.class_type_code='DCT_PROGRAM' AND m.segment_value=prod.dct_gl_class_pkg.norm(p.program_code,6));

COMMIT;
PROMPT GL seed loaded (sectors=21, chapters=7, programs=41).
