-- ===========================================================================
-- General Ledger (App 210) - master install
-- Run each in SQLcl: sql -name prod_mcp
-- IMPORTANT: 01 (synonyms) and 05 (ORDS) must each run in their OWN fresh
-- session (ORA-01471 self-referencing-synonym rule). Run 06 with
-- -Dfile.encoding=UTF-8 (Arabic class-type names).
-- ===========================================================================
-- @01_gl_synonyms.sql      -- fresh session
-- @02_gl_ddl.sql
-- @03_gl_pkg.sql
-- @04_gl_views.sql
-- @06_gl_seed.sql          -- JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
-- @05_gl_ords.sql          -- fresh session
-- @07_gl_budget_util_ords.sql      -- ADDITIVE, fresh session (re-run after any 05)
-- @08_gl_views_rebuild_ords.sql    -- ADDITIVE, fresh session (re-run after any 05)
-- @09_gl_class_drill_ords.sql      -- ADDITIVE (synced into 05; re-run after any 05)
-- @10_gl_actuals_lines_docnum.sql  -- ADDITIVE (synced into 05; re-run after any 05)
-- @11_gl_butil_book_ords.sql       -- ADDITIVE, fresh session (re-run after any 05)
-- @12_gl_encumbrances_ords.sql     -- ADDITIVE, fresh session (re-run after any 05)
-- @13_gl_pending_ords.sql          -- ADDITIVE, fresh session (re-run after any 05;
--                                      needs db/v2/52 view + reporting/db/23 seed)
PROMPT GL install: run scripts 01..13 individually per the header notes.
