prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/application_configuration.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/navigation/lists/service_providers_actions_list.sql
@@application/shared_components/navigation/lists/lookups_list.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/active_service_agreement_count.sql
@@application/shared_components/logic/application_items/emp_name.sql
@@application/shared_components/logic/application_items/emp_num.sql
@@application/shared_components/logic/application_items/person_id.sql
@@application/shared_components/logic/application_items/service_providers_count.sql
@@application/shared_components/logic/application_items/service_provider_id.sql
@@application/shared_components/logic/application_items/service_provider_name.sql
@@application/shared_components/logic/application_items/service_provider_num.sql
@@application/shared_components/logic/application_computations/active_service_agreement_count.sql
@@application/shared_components/logic/application_computations/service_providers_count.sql
@@application/shared_components/logic/application_computations/person_id.sql
@@application/shared_components/logic/application_computations/emp_num.sql
@@application/shared_components/logic/application_computations/emp_name.sql
@@application/shared_components/logic/application_computations/service_provider_id.sql
@@application/shared_components/logic/application_computations/service_provider_name.sql
@@application/shared_components/logic/application_computations/service_provider_num.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/risk_level_lov.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/banks_lov.sql
@@application/shared_components/user_interface/lovs/cost_centers_with_names_lov.sql
@@application/shared_components/user_interface/lovs/countries_lov.sql
@@application/shared_components/user_interface/lovs/currency_lov.sql
@@application/shared_components/user_interface/lovs/dct_person_types_active_lov.sql
@@application/shared_components/user_interface/lovs/dct_person_types_all_lov.sql
@@application/shared_components/user_interface/lovs/departments_lov.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/emp_full_name_by_person_id_lov.sql
@@application/shared_components/user_interface/lovs/employees_details_return_personid_popup.sql
@@application/shared_components/user_interface/lovs/expenditure_by_p6_project_and_p6_task_lov.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/fl_agreement_types_lov.sql
@@application/shared_components/user_interface/lovs/fl_payment_terms_lov.sql
@@application/shared_components/user_interface/lovs/fl_contract_duration.sql
@@application/shared_components/user_interface/lovs/fl_convsertion.sql
@@application/shared_components/user_interface/lovs/fl_locations.sql
@@application/shared_components/user_interface/lovs/fl_payment_cycle.sql
@@application/shared_components/user_interface/lovs/fl_technology_required.sql
@@application/shared_components/user_interface/lovs/freelancer_categories_active_lov.sql
@@application/shared_components/user_interface/lovs/freelancer_categories_all_lov.sql
@@application/shared_components/user_interface/lovs/freelancers_activities_lov.sql
@@application/shared_components/user_interface/lovs/full_name_return_person_id.sql
@@application/shared_components/user_interface/lovs/gender_lov.sql
@@application/shared_components/user_interface/lovs/gl_entities_lov.sql
@@application/shared_components/user_interface/lovs/initiatives_popup.sql
@@application/shared_components/user_interface/lovs/language_lov.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/nationality_lov.sql
@@application/shared_components/user_interface/lovs/non_cwip_projects_lov.sql
@@application/shared_components/user_interface/lovs/operational_projects.sql
@@application/shared_components/user_interface/lovs/organization_name_return_org_id.sql
@@application/shared_components/user_interface/lovs/organizations_with_cost_center_all_lov.sql
@@application/shared_components/user_interface/lovs/payments_periods_lov.sql
@@application/shared_components/user_interface/lovs/priority_lov.sql
@@application/shared_components/user_interface/lovs/programs.sql
@@application/shared_components/user_interface/lovs/projects_numbers_with_name_lov.sql
@@application/shared_components/user_interface/lovs/roles_lov.sql
@@application/shared_components/user_interface/lovs/sectors_lov.sql
@@application/shared_components/user_interface/lovs/service_agreement_number_by_id_lov.sql
@@application/shared_components/user_interface/lovs/service_provider_name_by_id_lov.sql
@@application/shared_components/user_interface/lovs/service_providers_lov.sql
@@application/shared_components/user_interface/lovs/status_lov.sql
@@application/shared_components/user_interface/lovs/task_number_by_p6_project_lov.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/title_lov.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/vendors_lov.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/shared_components/user_interface/lovs/yes_lov.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00030.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10020.sql
@@application/pages/page_10030.sql
@@application/pages/page_10031.sql
@@application/pages/page_10032.sql
@@application/pages/page_10033.sql
@@application/pages/page_10034.sql
@@application/pages/page_10040.sql
@@application/pages/page_10041.sql
@@application/pages/page_10042.sql
@@application/pages/page_10043.sql
@@application/pages/page_10044.sql
@@application/pages/page_10050.sql
@@application/pages/page_10051.sql
@@application/pages/page_10052.sql
@@application/pages/page_10053.sql
@@application/pages/page_10054.sql
@@application/pages/page_10060.sql
@@application/pages/page_10061.sql
@@application/end_environment.sql
