prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/data_load_wizard_progress_sap_sf_upload_data.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/data_load_wizard_progress_upload_payroll_elements.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/app_54293_logo_1_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/emp_name.sql
@@application/shared_components/logic/application_items/is_compensation_benifit_yn.sql
@@application/shared_components/logic/application_items/is_payroll_admin.sql
@@application/shared_components/logic/application_items/person_id.sql
@@application/shared_components/logic/application_computations/emp_name.sql
@@application/shared_components/logic/application_computations/person_id.sql
@@application/shared_components/logic/application_computations/is_compensation_benifit_yn.sql
@@application/shared_components/logic/application_computations/is_payroll_admin.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/ap_invoice_types.sql
@@application/shared_components/user_interface/lovs/ap_payments_methods_lov.sql
@@application/shared_components/user_interface/lovs/ap_payments_terms_lov.sql
@@application/shared_components/user_interface/lovs/countries_lov.sql
@@application/shared_components/user_interface/lovs/currency_lov.sql
@@application/shared_components/user_interface/lovs/data_load_charset.sql
@@application/shared_components/user_interface/lovs/data_load_option.sql
@@application/shared_components/user_interface/lovs/date_format_opt.sql
@@application/shared_components/user_interface/lovs/emirates_lov.sql
@@application/shared_components/user_interface/lovs/emirates_page12.sql
@@application/shared_components/user_interface/lovs/employees_all_lov.sql
@@application/shared_components/user_interface/lovs/employees_details_return_personid_popup.sql
@@application/shared_components/user_interface/lovs/end_user_approved_projects.sql
@@application/shared_components/user_interface/lovs/full_name_return_person_id.sql
@@application/shared_components/user_interface/lovs/grads_lov.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/mission_request_types.sql
@@application/shared_components/user_interface/lovs/pay_groups_lov.sql
@@application/shared_components/user_interface/lovs/priority_lov.sql
@@application/shared_components/user_interface/lovs/roles_lov.sql
@@application/shared_components/user_interface/lovs/scale_lov.sql
@@application/shared_components/user_interface/lovs/sectors_lov.sql
@@application/shared_components/user_interface/lovs/status_lov.sql
@@application/shared_components/user_interface/lovs/ticket_request_choices.sql
@@application/shared_components/user_interface/lovs/transportations_lov.sql
@@application/shared_components/user_interface/lovs/travel_class_lov.sql
@@application/shared_components/user_interface/lovs/vendors_with_bank_accounts.sql
@@application/shared_components/user_interface/lovs/yes_no_lov.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/reports/report_queries/insurance_statement.sql
@@application/shared_components/reports/report_queries/mission_query.sql
@@application/shared_components/reports/report_layouts/mission_report.sql
@@application/shared_components/reports/report_layouts/statement.sql
@@application/shared_components/email/templates/action_required_mission_old.sql
@@application/shared_components/email/templates/action_required_mission.sql
@@application/shared_components/email/templates/fyi_mission_finally_approved.sql
@@application/shared_components/email/templates/fyi_end_user_finally_rejected.sql
@@application/shared_components/email/templates/reminder_mission_action_required.sql
@@application/shared_components/email/templates/return_mission.sql
@@application/shared_components/security/authentications/dct_uat.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/shared_components/security/authentications/dct.sql
@@application/shared_components/plugins/dynamic_action/apex_profile_menu.sql
@@application/shared_components/plugins/dynamic_action/apex_notification.sql
@@application/shared_components/data_loading/tables/sf_employees_upload.sql
@@application/shared_components/data_loading/tables/rpa_payroll_elements_upload.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_09999.sql
@@application/end_environment.sql
