prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/data_load_wizard_progress_dp_items_staging.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/page_navigation.sql
@@application/shared_components/navigation/lists/application_configuration.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/navigation/lists/wizard_progress_list.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/dp_admin_role.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/current_year.sql
@@application/shared_components/logic/application_items/emp_name.sql
@@application/shared_components/logic/application_items/emp_num.sql
@@application/shared_components/logic/application_items/emp_org_id.sql
@@application/shared_components/logic/application_items/is_dp_admin.sql
@@application/shared_components/logic/application_items/is_fbp_emp.sql
@@application/shared_components/logic/application_items/is_ifinance_admin.sql
@@application/shared_components/logic/application_items/is_pbp_emp.sql
@@application/shared_components/logic/application_items/is_view_all_dp_items.sql
@@application/shared_components/logic/application_items/person_id.sql
@@application/shared_components/logic/application_items/user_cost_center.sql
@@application/shared_components/logic/application_computations/person_id.sql
@@application/shared_components/logic/application_computations/is_view_all_dp_items.sql
@@application/shared_components/logic/application_computations/is_pbp_emp.sql
@@application/shared_components/logic/application_computations/emp_name.sql
@@application/shared_components/logic/application_computations/emp_num.sql
@@application/shared_components/logic/application_computations/emp_org_id.sql
@@application/shared_components/logic/application_computations/is_fbp_emp.sql
@@application/shared_components/logic/application_computations/user_cost_center.sql
@@application/shared_components/logic/application_computations/is_ifinance_admin.sql
@@application/shared_components/logic/application_computations/is_dp_admin.sql
@@application/shared_components/logic/application_computations/current_year.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/category_order_level.sql
@@application/shared_components/user_interface/lovs/cost_centers_with_names_lov.sql
@@application/shared_components/user_interface/lovs/data_points_all_lov.sql
@@application/shared_components/user_interface/lovs/data_load_charset.sql
@@application/shared_components/user_interface/lovs/data_load_option.sql
@@application/shared_components/user_interface/lovs/date_format_opt.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/dp_item_category_roles.sql
@@application/shared_components/user_interface/lovs/dp_item_codes_by_item_id_lov.sql
@@application/shared_components/user_interface/lovs/dp_item_participant_roles.sql
@@application/shared_components/user_interface/lovs/dp_item_planning_status.sql
@@application/shared_components/user_interface/lovs/dp_item_status_active.sql
@@application/shared_components/user_interface/lovs/dp_item_status_all.sql
@@application/shared_components/user_interface/lovs/dp_item_types_lov.sql
@@application/shared_components/user_interface/lovs/dp_procurement_method.sql
@@application/shared_components/user_interface/lovs/dp_procurement_method_all.sql
@@application/shared_components/user_interface/lovs/dp_risk_level_lov.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/employees_details_return_personid_popup.sql
@@application/shared_components/user_interface/lovs/estimated_budget_bracket_lov.sql
@@application/shared_components/user_interface/lovs/expenditure_types_by_page_10.sql
@@application/shared_components/user_interface/lovs/expenditure_types_by_page_11.sql
@@application/shared_components/user_interface/lovs/expenditure_types_by_page_18.sql
@@application/shared_components/user_interface/lovs/expenditures_all.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/full_name_return_person_id.sql
@@application/shared_components/user_interface/lovs/futrure2_all.sql
@@application/shared_components/user_interface/lovs/initiatives_popup.sql
@@application/shared_components/user_interface/lovs/item_categories_all_lov.sql
@@application/shared_components/user_interface/lovs/item_categories_all_popup.sql
@@application/shared_components/user_interface/lovs/item_categories_popup.sql
@@application/shared_components/user_interface/lovs/item_category_lov.sql
@@application/shared_components/user_interface/lovs/item_category_roletype.sql
@@application/shared_components/user_interface/lovs/item_main_categories_lov.sql
@@application/shared_components/user_interface/lovs/item_main_categories_popup.sql
@@application/shared_components/user_interface/lovs/item_sub_categories_lov.sql
@@application/shared_components/user_interface/lovs/item_sub_cstegories_popup.sql
@@application/shared_components/user_interface/lovs/language_lov.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/months_lov.sql
@@application/shared_components/user_interface/lovs/mpr_procurement_methods.sql
@@application/shared_components/user_interface/lovs/objectives_and_benefits_record_types.sql
@@application/shared_components/user_interface/lovs/operational_projects.sql
@@application/shared_components/user_interface/lovs/organization_name_return_org_id.sql
@@application/shared_components/user_interface/lovs/priority_lov.sql
@@application/shared_components/user_interface/lovs/procurement_methods_class.sql
@@application/shared_components/user_interface/lovs/reminder_types.sql
@@application/shared_components/user_interface/lovs/roles_lov.sql
@@application/shared_components/user_interface/lovs/roles_dp.sql
@@application/shared_components/user_interface/lovs/scoping_appendixes_lov.sql
@@application/shared_components/user_interface/lovs/scoping_components_lov.sql
@@application/shared_components/user_interface/lovs/scoping_templates.sql
@@application/shared_components/user_interface/lovs/sectors_lov.sql
@@application/shared_components/user_interface/lovs/status_lov.sql
@@application/shared_components/user_interface/lovs/tasks_all_sample.sql
@@application/shared_components/user_interface/lovs/tasks_by_project_number_page_18.sql
@@application/shared_components/user_interface/lovs/tasks_by_project_number_page10.sql
@@application/shared_components/user_interface/lovs/tasks_by_project_number_page11.sql
@@application/shared_components/user_interface/lovs/technical_submission_lov.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/vendors_lov.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/shared_components/user_interface/lovs/yes_no_lov.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/reports/report_queries/item_status_report.sql
@@application/shared_components/email/templates/reminder_sd_action_required.sql
@@application/shared_components/email/templates/reminder_dp_item.sql
@@application/shared_components/email/templates/action_required_dp_item.sql
@@application/shared_components/email/templates/fyi_end_dp_item_finally_approved.sql
@@application/shared_components/email/templates/reminder_dp_item_action_required.sql
@@application/shared_components/email/templates/return_dp_item.sql
@@application/shared_components/email/templates/fyi_end_dp_item_finally_rejected.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/shared_components/security/authentications/dct.sql
@@application/shared_components/plugins/dynamic_action/apex_profile_menu.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_badge_list.sql
@@application/shared_components/plugins/dynamic_action/apex_notification.sql
@@application/shared_components/data_loading/tables/dp_items_stage.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00090.sql
@@application/pages/page_00091.sql
@@application/pages/page_00092.sql
@@application/pages/page_00093.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10020.sql
@@application/pages/page_10030.sql
@@application/pages/page_10031.sql
@@application/pages/page_10032.sql
@@application/pages/page_10033.sql
@@application/pages/page_10034.sql
@@application/pages/page_10040.sql
@@application/pages/page_10041.sql
@@application/pages/page_10042.sql
@@application/pages/page_10043.sql
@@application/pages/page_10044.sql
@@application/pages/page_10050.sql
@@application/pages/page_10051.sql
@@application/pages/page_10052.sql
@@application/pages/page_10053.sql
@@application/pages/page_10054.sql
@@application/pages/page_10060.sql
@@application/pages/page_10061.sql
@@application/end_environment.sql
